# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b6e4ed8a203733989fc5aa271de00cf667b161fdc0ac3e991fe904cd9142518096ff5f19dce455777dcdea633e275297768167a362b034d32b90aff4654b06

test:
  secret_key_base: 5516b87d87512504239370330207693a7d69222485430755c4de9027924cd9e696dcdce5a6581d3c675a260bdc13c734a5ff1ae1d19910085d90953656c418ea


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  key1: <%= ENV["key1"] %>
  key2: <%= ENV["key1"] %>
  key3: <%= ENV["key1"] %>


